name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run copy-wasms
      - run: npm run vsce
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./qavajs-*.vsix
      - name: publish to marketplace
        run: npx @vscode/vsce publish --pat ${{ secrets.VSCE_PAT }}
